[2018-05-07 16:10:38,635] WARN Attempting to send response via channel for which there is no open connection, connection id 10.0.0.2:9092-10.0.1.80:34048-6418 (kafka.network.Processor)
[2018-05-07 16:11:32,455] WARN Attempting to send response via channel for which there is no open connection, connection id 10.0.0.2:9092-10.0.1.228:53906-6418 (kafka.network.Processor)
[2018-05-07 16:11:32,457] WARN Attempting to send response via channel for which there is no open connection, connection id 10.0.0.2:9092-10.0.1.228:53910-6418 (kafka.network.Processor)
[2018-05-07 16:14:34,258] WARN [ReplicaFetcher replicaId=3, leaderId=1, fetcherId=0] Error in fetch to broker 1, request (type=FetchRequest, replicaId=3, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={__consumer_offsets-0=(offset=299678454, logStartOffset=187457977, maxBytes=1048576), __consumer_offsets-1=(offset=299923454, logStartOffset=187412386, maxBytes=1048576)}, isolationLevel=READ_UNCOMMITTED) (kafka.server.ReplicaFetcherThread)
java.io.IOException: Connection to 1 was disconnected before the response was read
        at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:95)
        at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:96)
        at kafka.server.ReplicaFetcherThread.fetch(ReplicaFetcherThread.scala:205)
        at kafka.server.ReplicaFetcherThread.fetch(ReplicaFetcherThread.scala:41)
        at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:149)
        at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:64)
